### PR TITLE
Show dashboard local tasks

### PR DESCRIPTION
**Pull request by penyaskito**
Dashboard issue: https://www.drupal.org/project/3327580/issues/3348617

Can be seen at https://pr9-1p46ghnin4p9kammaiawup7vofhc1eev.tugboatqa.com/

Use admin/admin or editor/editor

### CODE REVIEW

**Comment by plopesc** [comment]
It looks great! :rocket:

**Comment by penyaskito** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr9-1p46ghnin4p9kammaiawup7vofhc1eev.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/642998d2bdfd3ca2e136dc6d

**Comment by penyaskito** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr9-1p46ghnin4p9kammaiawup7vofhc1eev.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/642998d2bdfd3ca2e136dc6d

**Comment by penyaskito** [comment]
This has been pushed.

**Pull request closed without merging**
